spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
    resources:
      add-mappings: false
  application:
    name: FunQuiz
  profiles:
    active: dev
server:
  port: 5000



#  servlet:
#    context-path: /api
app:
  jwt:
    secret: xhs8v9CjR2nF7pLmQwErTyUiOpAsDfGh
    expiration: 3600000
#logging:
#  level:
#    root: ERROR