spring:
  data:
    redis:
      url: rediss://default:AVNS_9Gibmk8om2RAV0VOhIH@valkey-snaapio-skysolo007.b.aivencloud.com:28574
      database: 0
      ssl:
        enabled: true
    mongodb:
      uri: mongodb+srv://springboot:Lf10YKyQcNv72Fjv@akashmondal0.u1f8e.mongodb.net/springboot
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mondal2003sky@gmail.com
    password: cyrn xktr llgm iifv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400 # 24 hours in seconds
  refresh-expiration: 604800 # 7 days in seconds