spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: MagicKitchen
  profiles:
    active: dev
server:
  port: 5000


#  servlet:
#    context-path: /api
app:
  jwt:
    secret: xhs8v9CjR2nF7pLmQwErTyUiOpAsDfGh
    expiration: 3600000
#logging:
#  level:
#    root: ERROR