spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
    resources:
      add-mappings: false
  application:
    name: FunQuiz
  profiles:
    active: dev
server:
  port: 5000
#  servlet:
#    context-path: /api
# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 2592000000 # 30 days in seconds
  refresh-expiration: 604800 # 7 days in seconds
#logging:
#  level:
#    root: ERROR