spring:
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      url: REPLACE_ME
      database: 0
    mongodb:
      uri: REPLACE_ME
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: REPLACE_ME
    password: REPLACE_ME
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
genai:
  apiKey: REPLACE_ME
  modelUrl: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=